version: "3.9"

services:
  apollo-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      # NODE_ENV: production
      APP_SECRET: "eric-tech-graphql-tutorial"
      DATABASE_URL: "postgresql://prisma:prisma@postgres:5432/mydb"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
